#!/usr/bin/env bash
set -euo pipefail

# Writes Owl/Support/Local.xcconfig from .env, so that a plain `xcodebuild`,
# the Run button in Xcode, and skills/install-to-local all build with the same
# metadata service key that scripts/release.sh passes on its command line.
#
# The generated file is gitignored. Running this with no .env, or with no key
# in it, is not an error: it writes an empty key, which is the same as having
# none.

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="$ROOT/Owl/Support/Local.xcconfig"

key=""
if [[ -f "$ROOT/.env" ]]; then
  # Read the assignment rather than sourcing the file, so a stray command in
  # .env cannot run and the other credentials in it stay out of this process.
  key="$(sed -n 's/^[[:space:]]*TMDB_API_KEY[[:space:]]*=[[:space:]]*//p' "$ROOT/.env" | tail -n 1)"
  # Tolerate a quoted value.
  key="${key%\"}"; key="${key#\"}"
  key="${key%\'}"; key="${key#\'}"
fi

umask 077
cat > "$CONFIG" <<CFG
// Generated by scripts/write-local-config.sh — do not edit, and do not commit.
TMDB_API_KEY = $key
CFG

if [[ -n "$key" ]]; then
  echo "✅ Wrote a metadata service key to Owl/Support/Local.xcconfig"
else
  echo "ℹ️  No TMDB_API_KEY in .env; metadata sync will be unavailable in this build"
fi
